export const language = {
  title: 'Countries',
  github: 'Github',
  youtube: 'Youtube',
  countries: 'Countries',
  total: 'Total',
  loading: 'Loading',
  noresult: 'No result found',
  thanks: 'Thanks to',
  year: '2020',
  flaticon: 'FlatIcon for icons',
  restcountries: 'Restcountries for api',
  psdgraphic: 'Psdgraphics for background image',
  name: 'Name',
  topLevelDomain: 'Domain',
  alpha2Code: 'Alpha 2 Code',
  alpha3Code: 'Alpha 3 Code',
  callingCodes: 'Calling Codes',
  capital: 'Capital',
  altSpellings: 'Alt Spellings',
  region: 'Region',
  subregion: 'Sub Region',
  population: 'Population',
  latlng: 'Latitude / Longitude',
  demonym: 'Demonym',
  area: 'Area',
  gini: 'Gini',
  timezones: 'Timezones',
  borders: 'Borders',
  nativeName: 'Native Name',
  numericCode: 'Numeric Code',
  currencies: 'Currencies',
  languages: 'Languages',
  translations: 'Translations',
  flag: 'Flag Url',
  regionalBlocs: 'Regional Blocs',
  cioc: 'Cioc'

}
